### ISSUE TITLE
updateActivePagerLink remains active after pausing

### ISSUE THREAD

**Issue by jzfgo** [malsup/cycle#9]
I noticed this when updating from v2.75. When I call `$.cycle('pause')` the animation pauses, by the pagination keeps going.

Runing a diff between last and this version shows that the following code block is now outside an `if` statement that checks if the animation is paused.

```
// calculate the next slide
opts.lastSlide = opts.currSlide;
if (opts.random) {
    opts.currSlide = opts.nextSlide;
    if (++opts.randomIndex == els.length)
        opts.randomIndex = 0;
    opts.nextSlide = opts.randomMap[opts.randomIndex];
    if (opts.nextSlide == opts.currSlide)
        opts.nextSlide = (opts.currSlide == opts.slideCount - 1) ? 0 : opts.currSlide + 1;
}
else { // sequence
    var roll = (opts.nextSlide + 1) == els.length;
    opts.nextSlide = roll ? 0 : opts.nextSlide+1;
    opts.currSlide = roll ? els.length-1 : opts.nextSlide-1;
}

if (opts.pager)
    opts.updateActivePagerLink(opts.pager, opts.currSlide, opts.activePagerClass);
```

**Comment by binhdo** [comment]
Same here with 'pause' and 'pauseOnPagerHover' set to true in the latest version. Simple example on my band's page: http://dangerbeuys.de
When hovering the content or navigation, the pager keeps on cycling.

**Comment by malsup** [comment]
Fixed in 2.84.  Thanks for catching this bug!

**Comment by jzfgo** [comment]
Thank you always Mike, this plugin is great.

But I'm afraid it's still not fixed. The current page updates at init, but not on page change when paused. I compiled a quick example so you can see it better:

http://javierzapata.es/cyclebug/

**Comment by malsup** [comment]
Thanks for the feedback.  I think v2.85 fixes this.
http://github.com/malsup/cycle/raw/master/jquery.cycle.all.js

**Comment by jzfgo** [comment]
It's fixed in my case. Thanks.
